name: Node.js CI

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
    
      - name: Instal dependencies
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Install Allure
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: allure generate --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
